config/routes.rb
Rails.application.routes.draw do
  root 'pages#dashboard' # shortcut for the abov
  resources :employees
  resources :departements, only: [:index, :show] do
    resources :teams, only: [:show]
  end
  
  resources :allowances
  resources :payslip_allowances, only: [:destroy]
  resources :deductions
  resources :payslip_deductions, only: [:destroy]
  resources :payslips do
    member do
      get 'dowload'
      get 'preview'
      post 'increase_present_days'
      post 'decrease_present_days'
      post 'increase_absent_days'
      post 'decrease_absent_days'
    end
  end
  get 'payslips/pdf/:id', to: 'payslips#generate_payslip', as: 'generate_payslip'
  resources :teams, only: [:index, :new, :create]
end 

app/models/payslip.rb
class Payslip < ApplicationRecord
  belongs_to :employee
  # has_one_attached :pdf
  has_many :payslip_allowances, dependent: :destroy
  has_many :allowances, through: :payslip_allowances
  has_many :payslip_deductions, dependent: :destroy
  has_many :deductions, through: :payslip_deductions

  validates :present, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
}

validates :absent, numericality: {
  only_integer: true,
  greater_than_or_equal_to: 0
}

  def calculate_allowances_amount
    self.allowances.sum(:amount)
  end

  def calculate_deductions_amount
    self.deductions.sum(:amount)
  end
end

app/controllers/payslips_controller.rb
class PayslipsController < ApplicationController
  before_action :set_payslip, only: %i[ show edit update increase_present_days increase_absent_days decrease_present_days decrease_absent_days dowload generate_payslip]
  require "prawn"

  def index
    @payslips = Payslip.all
    @employees = Employee.all.order('last_name ASC')
  end

  def show
    @allowances = Allowance.where(payslip_id: @payslip)
    @deductions = Deduction.where(payslip_id: @payslip)
  end

  def new
    @payslip = Payslip.new
    @payslip.allowances.build
    @payslip.deductions.build
  end

  def create
    @payslip = Payslip.new(payslip_params)
    if @payslip.save
      redirect_to payslips_url, notice: 'payslip was successfully created.'
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @payslip.update(payslip_params)
      @payslip.update(allowance_amount: @payslip.calculate_allowances_amount, deduction_amount: @payslip.calculate_deductions_amount)
      redirect_to payslip_url(@payslip), notice: "Payslip was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def generate_payslip
    pdf = Prawn::Document.new
    pdf.text "Payslip for #{@payslip.employee.fullname}", size: 24, style: :bold, align: :center
    pdf.move_down 100

    pdf.text "EMPLOYEE'S INFORMATION", size: 16
    pdf.move_down 10
    pdf.text "<b>Employee Name:</b> #{@payslip.employee.fullname}", size: 14, inline_format: true
    pdf.text "<b>Employee Address:</b> #{@payslip.employee.city}, #{@payslip.employee.country}", size: 14, inline_format: true
    pdf.text "<b>Employee Position:</b> #{@payslip.employee.position.name.capitalize} in #{@payslip.employee.team.name.capitalize} team", size: 14, inline_format: true
    pdf.move_down 40

    pdf.text "PRESENCE INFORMATION", size: 16
    pdf.move_down 10
    pdf.text "<b>Days of presence:</b> #{@payslip.present}", size: 14, inline_format: true
    pdf.text "<b>Days of absence:</b> #{@payslip.absent}", size: 14, inline_format: true
    pdf.move_down 40

    pdf.text "EARNINGS", size: 16
    pdf.move_down 10
    pdf.text "<b>Brut salary:</b> $#{@payslip.salary}", size: 14, inline_format: true
    pdf.move_down 15
    pdf.text "List of allowances", size: 14, style: :italic
    pdf.move_down 10
    @payslip.allowances.each do |allowance|
      pdf.text "• #{allowance.name}: #{allowance.amount} pts", size: 12, inline_format: true
      pdf.move_down 10
    end
    pdf.text "<b>Total allowances amount:</b> $#{@payslip.allowance_amount}", size: 14, inline_format: true
    pdf.move_down 15
    pdf.text "List of deductions", size: 14, style: :italic
    pdf.move_down 10
    @payslip.deductions.each do |deduction|
      pdf.text "• #{deduction.name}: #{deduction.amount} pts", size: 12
      pdf.move_down 10
    end
    pdf.text "<b>Total deductions amount:</b> $#{@payslip.deduction_amount}", size: 14, inline_format: true
    pdf.move_down 40

    pdf.text "Net Pay: $#{@payslip.net}", style: :bold, size: 18, align: :right

    send_data(pdf.render,
      filename: "Payslip_#{@payslip.employee.last_name}.pdf",
            type: 'application/pdf', 
            disposition: 'inline',
            page_size: 'A4'
          )
  end

  def increase_present_days
    @payslip.update(present: @payslip.present + 1)
    redirect_to @payslip
  end

  def decrease_present_days
    @payslip.update(present: @payslip.present - 1)
    redirect_to @payslip
  end

  def increase_absent_days
    @payslip.update(absent: @payslip.absent + 1)
    redirect_to @payslip
  end

  def decrease_absent_days
    @payslip.update(absent: @payslip.absent - 1)
    redirect_to @payslip
  end



  private
    def set_payslip
      @payslip = Payslip.find(params[:id])
    end

    def payslip_params
      params.require(:payslip).permit(:present, :employee, :absent, :salary, :allowance_amount, :deduction_amount, :net, allowance_ids:[], deduction_ids:[] )
    end
end

app/helpers/payslips_helper.rb
module PayslipsHelper
end

app/views/payslips/_form.html.erb
<%= simple_form_for @payslip, remote: true, html: { class: " p-2 mt-3"}, data: { turbo_frame: "_top" } do |f| %>
  <div class="form-inputs">
    <div>
      <h2 class="text-base font-semibold my-3">Configure presence</h2>
      <%= f.input :present, as: :numeric %>
      <%= f.input :absent, as: :numeric %>
    </div>
    <div>
      <h2 class="text-base font-semibold my-3">Configure salary</h2>
      <%= f.input :salary, as: :numeric %>
      <%= f.input :net, as: :numeric %>
    </div>
    <div>
      <h2 class="text-base font-semibold my-3">Configure taxation</h2>
      <div>
        <h3 class="font-light my-2"> Choose one or more allowances</h3>
        <div class="grid gap-x-8 gap-y-4 grid-cols-3">
          <%= f.collection_check_boxes :allowance_ids, Allowance.all, :id, :name do |b| %>
            <div class="mx-2 my-2 inline-flex">
              <span class="ml-2"><%= b.check_box %></span>
              <span class="ml-2"><%= b.label %></span>
            </div>
          <% end %>
        </div>
        
        <h3 class="font-light my-2"> Choose one or more deductions</h3>
        <div class="grid gap-x-8 gap-y-4 grid-cols-3">
          <%= f.collection_check_boxes :deduction_ids, Deduction.all, :id, :name do |b| %>
          <div class="mx-2 my-2 inline-flex">
            <span class="ml-2"><%= b.check_box %></span>
            <span class="ml-2"><%= b.label %></span>
          </div>
          <% end %>
        </div>
    </div>
  </div>
  <div class="px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
    <%= button_to 'Cancel', payslip_path(@payslip), class:"mt-3 inline-flex w-full justify-center rounded-md px-3 py-2 text-sm font-semibold text-gray-800 shadow-sm ring-1 ring-inset ring-gray-800 hover:bg-gray-50 sm:mt-0 sm:w-auto" %>  
    <%= f.submit 'Update', class:"mt-3 inline-flex w-full justify-center rounded-md px-3 py-2 text-sm font-semibold text-gray-800 shadow-sm ring-1 ring-inset ring-gray-800 hover:bg-gray-50 sm:mt-0 sm:w-auto" %>
  </div>
<% end %>

app/views/payslips/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Payslips#create</h1>
  <p>Find me in app/views/payslips/create.html.erb</p>
</div>

app/views/payslips/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>
    <div class="fixed inset-0 z-10 overflow-y-auto">
      <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
        <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg" >
          <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
              <%= button_to 'X', payslip_path(@payslip), class:"absolute top-4 right-4", data: { turbo_frame: "_top" } %>
            <div>
              <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
                <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title">Edit payslip's information</h3>
                <div class="mt-2">
                  <%= render 'payslips/form' %>
                </div>
              </div>
            </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/payslips/index.html.erb
<div class="p-6 sm:p-10 space-y-6 h-screen w-screen">
  <div class="flex flex-col space-y-6 md:space-y-0 md:flex-row justify-between">
    <div class="mr-6">
      <h1 class="text-4xl font-semibold mb-2">Payslip Dashboard</h1>
    </div>
  </div> 
  <section class="grid md:grid-cols-2 xl:grid-cols-4 gap-6">
    <% @payslips.each do |payslip| %>
      <div class="flex items-center p-8 bg-white shadow rounded-lg">
        <div>
          <span class="block text-2xl font-bold"><%= payslip.employee.fullname %></span>
          <span class="block text-gray-500"><%= link_to 'Show', payslip_path(payslip) %></span>
        </div>
      </div>
    <% end %>
  </section>    
</div>

app/views/payslips/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Payslips#new</h1>
  <p>Find me in app/views/payslips/new.html.erb</p>
</div>

app/views/payslips/show.html.erb
<div class="flex flex-col h-screen justify-center items-center text-center">
    <div class="flex flex-col items-center my-3">
        <div class="py-12 flex flex-col items-center">
            <h1 class="font-serif text-2xl font-extrabold tracking-widest uppercase"><%= @payslip.employee.fullname %></h1>
            <h2 class="font-serif text-1xl font-extrabold tracking-widest"><%= @payslip.employee.departement.name %></h2>
            <%= link_to 'View PDF', generate_payslip_path(@payslip), class:"font-serif text-1xl tracking-widest " %>
            <%= link_to edit_payslip_path(@payslip), data: { turbo_frame: "modal" } do %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 font-serif text-1xl font-extrabold tracking-widest text-red-400">
                <path d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32l8.4-8.4z" />
                <path d="M5.25 5.25a3 3 0 00-3 3v10.5a3 3 0 003 3h10.5a3 3 0 003-3V13.5a.75.75 0 00-1.5 0v5.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5V8.25a1.5 1.5 0 011.5-1.5h5.25a.75.75 0 000-1.5H5.25z" />
                </svg>
            <% end %>
        </div>
    </div>
    <div class="flex flex-col w-full overflow-y-auto px-8 py-3">
      <div class="flex flex-col my-3">
          <span class="flex items-start my-4 mx-2 text-2xl font-light ">Configure presence</span>
          <div class="grid md:grid-cols-2 xl:grid-cols-4 gap-6">
              <div class="flex flex-row p-8 bg-white shadow rounded-lg">
                  <div class="flex-1 w-1/2">
                    <span class="flex text-xl font-bold">Presence</span>
                    <span class="flex items-start text-gray-500"><%= @payslip.present %> days</span>
                  </div>
                  <div class="flex-1 w-1/2">
                    <%= button_to increase_present_days_payslip_path(@payslip), method: :post do %>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-red-800">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                        </svg>
                    <% end %>
                    <%= button_to decrease_present_days_payslip_path(@payslip), method: :post do %>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-red-800">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15" />
                        </svg>
                    <% end %>
                  </div>
              </div>
              <div class="flex flex-row p-8 bg-white shadow rounded-lg">
                  <div class="flex-1 w-1/2">
                      <span class="flex text-xl font-bold">Absence</span>
                      <span class="flex items-start text-gray-500"><%= @payslip.absent %> days</span>
                  </div>
                  <div class="flex-1 w-1/2">
                    <%= button_to increase_absent_days_payslip_path(@payslip), method: :post do %>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-red-800">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                        </svg>
                    <% end %>
                    <%= button_to decrease_absent_days_payslip_path(@payslip), method: :post do %>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-red-800">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15" />
                        </svg>
                    <% end %>
                  </div>
              </div>
          </div>
      </div>
      <div class="flex flex-col my-3">
          <span class="flex items-start my-4 mx-2 text-2xl font-light ">Configure salary</span>
          <div class="grid md:grid-cols-2 xl:grid-cols-4 gap-6">
              <div class="flex items-center p-8 bg-white shadow rounded-lg">
                  <div>
                      <span class="flex text-xl font-bold">Salary</span>
                      <span class="flex items-start text-gray-500"><%= @payslip.salary %> €</span>
                  </div>
              </div>
              <div class="flex items-center p-8 bg-white shadow rounded-lg">
                  <div>
                      <span class="flex text-xl font-bold">Net</span>
                      <span class="flex items-start text-gray-500"><%= @payslip.net %> €</span>
                  </div>
              </div>
          </div>
      </div>
      <div class="flex flex-col my-3">
          <span class="flex items-start my-4 mx-2 text-2xl font-light ">Configure taxes</span>
            <div class="grid md:grid-cols-2 xl:grid-cols-4 xl:grid-rows-3 xl:grid-flow-col gap-6 my-4">
                <div class="row-span-3 bg-white shadow rounded-lg">
                    <div class="flex items-center justify-between px-6 py-5 font-semibold border-b border-gray-100">
                        <span class="flex text-xl font-bold">Allowances</span>
                    </div>
                    <div class="overflow-y-auto" style="max-height: 24rem;">
                        <% if @payslip.allowances.none? %>
                            <div class="flex items-center justify-center text-base text-gray-500  my-2 mx-2">
                                <span class="p-2 break-all">You should add allowances
                                </span>
                            </div>
                        <% else %>
                            <div class="grid grid-cols-3 gap-3">
                                <% @payslip.allowances.each do |a| %>
                                    <div class="flex items-center justify-center text-base  text-gray-500 bg-red-300 rounded-lg my-2 mx-2">
                                    <span class="p-2 break-all"><%= a.name %>
                                    </span>
                                    </div>
                                <% end %> 
                            </div>
                        <% end %>
                    </div>
                </div>
                <div class="row-span-3 bg-white shadow rounded-lg">
                    <div class="flex items-center justify-between px-6 py-5 font-semibold border-b border-gray-100">
                        <span class="flex text-xl font-bold">Deductions</span>
                    </div>
                    <div class="overflow-y-auto" style="max-height: 24rem;">
                        <% if @payslip.deductions.none? %>
                            <div class="flex items-center justify-center text-base text-gray-500  my-2 mx-2">
                                <span class="p-2 break-all">You should add deductions
                                </span>
                            </div>
                        <% else %>
                            <div class="grid grid-cols-3 gap-3">
                                <% @payslip.deductions.each do |d| %>
                                    <div class="flex items-center justify-center text-base  text-gray-500 bg-red-300 rounded-lg my-2 mx-2">
                                    <span class="p-2 break-all"><%= d.name %>
                                    </span>
                                    </div>
                                <% end %> 
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
          <div class="grid md:grid-cols-2 xl:grid-cols-4 gap-6">
              <div class="flex items-center p-8 bg-white shadow rounded-lg">
                  <div>
                      <span class="flex text-xl font-bold">Allowances amount</span>
                      <span class="flex items-start text-gray-500"><%= @payslip.allowance_amount %></span>
                  </div>
              </div>
              <div class="flex items-center p-8 bg-white shadow rounded-lg">
                  <div>
                      <span class="flex text-xl font-bold">Deductions amount</span>
                      <span class="flex items-start text-gray-500"><%= @payslip.deduction_amount %></span>
                  </div>
              </div>
          </div>
      </div>
    </div>
</div>

app/views/payslips/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Payslips#update</h1>
  <p>Find me in app/views/payslips/update.html.erb</p>
</div>