config/routes.rb
Rails.application.routes.draw do
  root 'pages#dashboard' # shortcut for the abov
  resources :employees
  resources :departements, only: [:index, :show] do
    resources :teams, only: [:show]
  end
  
  resources :allowances
  resources :payslip_allowances, only: [:destroy]
  resources :deductions
  resources :payslip_deductions, only: [:destroy]
  resources :payslips do
    member do
      get 'dowload'
      get 'preview'
      post 'increase_present_days'
      post 'decrease_present_days'
      post 'increase_absent_days'
      post 'decrease_absent_days'
    end
  end
  get 'payslips/pdf/:id', to: 'payslips#generate_payslip', as: 'generate_payslip'
  resources :teams, only: [:index, :new, :create]
end 

app/models/allowance.rb
class Allowance < ApplicationRecord
    before_validation :capitalize_name

    has_many :payslip_allowances, dependent: :destroy
    has_many :payslips, through: :payslip_allowances

    validates :name, :description, :amount, presence: true
    validates :name, uniqueness: true
  
    private
  
    def capitalize_name
      self.name = name.capitalize
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deduction.rb
class Deduction < ApplicationRecord
    before_validation :capitalize_name

    has_many :payslip_deductions, dependent: :destroy
    has_many :payslips, through: :payslip_deductions

    validates :name, uniqueness: true
    validates :name, :description, :amount, presence: true

    private
  
    def capitalize_name
      self.name = name.capitalize
    end
end

app/models/departement.rb
class Departement < ApplicationRecord
    has_many :teams
    has_many :employees, through: :teams

    validates :name, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :team, optional: true
  has_many :payslip

  has_one :departement, through: :team
  belongs_to :position, optional: true

  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]

  before_validation :set_default_values

  def fullname
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def avatar_thumbnail
    avatar.variant(resize_to_limit: [300,300]).processed
  end
  
  def tbd_team?
    self.team.name == 'TBD'
  end

  def tbd_position?
    self.position.name == 'TBD'
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[first_name last_name]
  end

  def self.ransackable_associations(auth_object = nil)
    ["avatar_attachment", "avatar_blob", "departement", "payslip", "position", "team"]
  end

  private

  def add_default_avatar
    return if self.avatar.attached?
    avatar.attach(
      io:
        File.open(Rails.root.join("app", "assets", "images", "anonymous.jpg")),
      filename: "anonymous.jpg",
      content_type: "image/jpg",
    )
  end

  def set_default_values
    self.position ||= Position.find_or_create_by(name: 'TBD')
    self.team ||= Team.find_or_create_by(name: 'TBD')
  end
end

app/models/payslip.rb
class Payslip < ApplicationRecord
  belongs_to :employee
  # has_one_attached :pdf
  has_many :payslip_allowances, dependent: :destroy
  has_many :allowances, through: :payslip_allowances
  has_many :payslip_deductions, dependent: :destroy
  has_many :deductions, through: :payslip_deductions

  validates :present, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
}

validates :absent, numericality: {
  only_integer: true,
  greater_than_or_equal_to: 0
}

  def calculate_allowances_amount
    self.allowances.sum(:amount)
  end

  def calculate_deductions_amount
    self.deductions.sum(:amount)
  end
end

app/models/payslip_allowance.rb
class PayslipAllowance < ApplicationRecord
    belongs_to :payslip
    belongs_to :allowance

    validates :allowance_id, uniqueness: {
        scope: [ :payslip_id ]
      }
end

app/models/payslip_deduction.rb
class PayslipDeduction < ApplicationRecord
    belongs_to :payslip
    belongs_to :deduction
end

app/models/position.rb
class Position < ApplicationRecord
    has_many :employees

    # validates :name, uniqueness: true
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :employees
    belongs_to :departement

    validates :name, uniqueness: true
    # enum :name, { 
    #     "HR": 0, 
    #     "Accounting": 1,
    #     "Financial controller": 2,
    #     "Legal": 3, 
    #     "IT Project management": 4, 
    #     "Project team": 5,
    #     "Help Desk": 6,
    #     "Client Support": 7,
    #     "IT Architecture": 8,
    #     "IT Applications": 9,
    #     "Managers": 10, 
    #     "Top Management": 11
    # }
end

app/controllers/departements_controller.rb
class DepartementsController < ApplicationController
  before_action :set_departement, only: %i[ show ]

  def index
    @tbd_dpt = Departement.where(name: 'TBD')
    @departements = Departement.all.order('name ASC').excluding(@tbd_dpt)
    Team.new
  end

  def show
  end

  private
  
  def set_departement
    @departement = Departement.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @employees_count = Employee.count
    # @tbd_position = Employee.where(position: 'TBD')
    # @tbd_team = Employee.where(team: 'TBD')
    # @tbd_dpt = Team.joins(:departement).where(departements: {name: 'TBD'})
    @employees = Employee.all.order('last_name ASC').excluding(@tbd_employees)
    @managers = Employee.where(manager: true).order('last_name ASC')
    @employee = Employee.new
    @tbd_employees = Employee.joins(:position, :team).where("positions.name = 'TBD' OR teams.name = 'TBD'")
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @results = Employee.search(params[:search])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show ]
  before_action :set_departement, only: %i[ show ]

  def index
    @teams = Team.all.order('name ASC')
  end

  def show
    @team_manager = Employee.find_by(team_id: @team, manager: true)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to departements_path, notice: 'A new team was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  
  def set_departement
    @departement = Departement.find(params[:departement_id])
  end

  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name, :description, :departement_id)
  end
end

app/helpers/allowances_helper.rb
module AllowancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/departements_helper.rb
module DepartementsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payslips_helper.rb
module PayslipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/departements/index.html.erb
<div class="flex flex-col p-6 sm:p-10 space-y-6 relative h-screen w-screen">
  <div id="overlay" class="fixed inset-0 bg-gray-800 opacity-75 hidden"></div>
  <div class="flex flex-col space-y-6 md:space-y-0 md:flex-row justify-between">
    <h1 class="text-4xl font-semibold mb-2">Departements Dashboard</h1>
    <%= link_to 'Create new team', new_team_path, data: { turbo_frame: "modal" }, class:'flex justify-center bg-red-500 hover:bg-red-700 font-bold py-2 px-4 rounded' %>
  </div>
  <div class="flex flex-col overflow-y-auto px-5 py-3">
    <div class="grid md:grid-cols-2 xl:grid-cols-4 gap-6 py-6" >
      <% @departements.each do |d| %>
        <button data-box="<%= d.id%>" class="taxation-button btn-ouline box flex items-center p-8 bg-white shadow rounded-lg">
            <div class="inline-flex flex-shrink-0 items-center justify-center h-16 w-16 text-purple-600 bg-purple-100 rounded-full mr-6">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
                <path fill-rule="evenodd" d="M1.5 7.125c0-1.036.84-1.875 1.875-1.875h6c1.036 0 1.875.84 1.875 1.875v3.75c0 1.036-.84 1.875-1.875 1.875h-6A1.875 1.875 0 011.5 10.875v-3.75zm12 1.5c0-1.036.84-1.875 1.875-1.875h5.25c1.035 0 1.875.84 1.875 1.875v8.25c0 1.035-.84 1.875-1.875 1.875h-5.25a1.875 1.875 0 01-1.875-1.875v-8.25zM3 16.125c0-1.036.84-1.875 1.875-1.875h5.25c1.036 0 1.875.84 1.875 1.875v2.25c0 1.035-.84 1.875-1.875 1.875h-5.25A1.875 1.875 0 013 18.375v-2.25z" clip-rule="evenodd" />
              </svg>
            </div>
            <div>
              <span class="block text-2xl font-bold"><%= d.name %></span>
            </div>
        </button>
        <div data-modal="<%= d.id%>" class="taxation-modal fixed inset-0 flex flex-col items-center justify-center p-8 hidden">
          <div class="bg-none p-4">
            <button type="button" class="closeModalButton sm:mx-0 w-full text-white font-wold text-xl flex justify-end py-3 my-3">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
            <% if d.teams.empty? %>
              <h1 class="uppercase text-start text-white font-bold text-xl">There is not team associated to this departement!</h1>
            <% else %>
              <h1 class="uppercase text-start text-white font-bold text-xl"><%= d.teams.count %> teams in <%= d.name %></h1>
              <div class="teams flex flex-col md:flex-row items-center justify-center">
                <div class="sm:flex sm:items-start">
                  <% d.teams.each do |t| %>
                    <div class="circle-team rounded-full bg-gray-800 text-pink-200 w-48 h-48 flex align-center justify-center items-center my-3 mx-3">
                      <h2 class="text-xl font-semibold"><%= link_to t.name, departement_team_path(d.id, t) %></h2>
                    </div>
                  <% end %>
                </div>
              </div> 
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>