config/routes.rb
Rails.application.routes.draw do
  root 'pages#dashboard' # shortcut for the abov
  resources :employees
  resources :departements, only: [:index, :show] do
    resources :teams, only: [:show]
  end
  
  resources :allowances
  resources :payslip_allowances, only: [:destroy]
  resources :deductions
  resources :payslip_deductions, only: [:destroy]
  resources :payslips do
    member do
      get 'dowload'
      get 'preview'
      post 'increase_present_days'
      post 'decrease_present_days'
      post 'increase_absent_days'
      post 'decrease_absent_days'
    end
  end
  get 'payslips/pdf/:id', to: 'payslips#generate_payslip', as: 'generate_payslip'
  resources :teams, only: [:index, :new, :create]
end 

app/models/allowance.rb
class Allowance < ApplicationRecord
    before_validation :capitalize_name

    has_many :payslip_allowances, dependent: :destroy
    has_many :payslips, through: :payslip_allowances

    validates :name, :description, :amount, presence: true
    validates :name, uniqueness: true
  
    private
  
    def capitalize_name
      self.name = name.capitalize
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deduction.rb
class Deduction < ApplicationRecord
    before_validation :capitalize_name

    has_many :payslip_deductions, dependent: :destroy
    has_many :payslips, through: :payslip_deductions

    validates :name, uniqueness: true
    validates :name, :description, :amount, presence: true

    private
  
    def capitalize_name
      self.name = name.capitalize
    end
end

app/models/departement.rb
class Departement < ApplicationRecord
    has_many :teams
    has_many :employees, through: :teams

    validates :name, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :team, optional: true
  has_many :payslip

  has_one :departement, through: :team
  belongs_to :position, optional: true

  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]

  before_validation :set_default_values

  def fullname
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def avatar_thumbnail
    avatar.variant(resize_to_limit: [300,300]).processed
  end
  
  def tbd_team?
    self.team.name == 'TBD'
  end

  def tbd_position?
    self.position.name == 'TBD'
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[first_name last_name]
  end

  def self.ransackable_associations(auth_object = nil)
    ["avatar_attachment", "avatar_blob", "departement", "payslip", "position", "team"]
  end

  private

  def add_default_avatar
    return if self.avatar.attached?
    avatar.attach(
      io:
        File.open(Rails.root.join("app", "assets", "images", "anonymous.jpg")),
      filename: "anonymous.jpg",
      content_type: "image/jpg",
    )
  end

  def set_default_values
    self.position ||= Position.find_or_create_by(name: 'TBD')
    self.team ||= Team.find_or_create_by(name: 'TBD')
  end
end

app/models/payslip.rb
class Payslip < ApplicationRecord
  belongs_to :employee
  # has_one_attached :pdf
  has_many :payslip_allowances, dependent: :destroy
  has_many :allowances, through: :payslip_allowances
  has_many :payslip_deductions, dependent: :destroy
  has_many :deductions, through: :payslip_deductions

  validates :present, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
}

validates :absent, numericality: {
  only_integer: true,
  greater_than_or_equal_to: 0
}

  def calculate_allowances_amount
    self.allowances.sum(:amount)
  end

  def calculate_deductions_amount
    self.deductions.sum(:amount)
  end
end

app/models/payslip_allowance.rb
class PayslipAllowance < ApplicationRecord
    belongs_to :payslip
    belongs_to :allowance

    validates :allowance_id, uniqueness: {
        scope: [ :payslip_id ]
      }
end

app/models/payslip_deduction.rb
class PayslipDeduction < ApplicationRecord
    belongs_to :payslip
    belongs_to :deduction
end

app/models/position.rb
class Position < ApplicationRecord
    has_many :employees

    # validates :name, uniqueness: true
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :employees
    belongs_to :departement

    validates :name, uniqueness: true
    # enum :name, { 
    #     "HR": 0, 
    #     "Accounting": 1,
    #     "Financial controller": 2,
    #     "Legal": 3, 
    #     "IT Project management": 4, 
    #     "Project team": 5,
    #     "Help Desk": 6,
    #     "Client Support": 7,
    #     "IT Architecture": 8,
    #     "IT Applications": 9,
    #     "Managers": 10, 
    #     "Top Management": 11
    # }
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @employees_count = Employee.count
    # @tbd_position = Employee.where(position: 'TBD')
    # @tbd_team = Employee.where(team: 'TBD')
    # @tbd_dpt = Team.joins(:departement).where(departements: {name: 'TBD'})
    @employees = Employee.all.order('last_name ASC').excluding(@tbd_employees)
    @managers = Employee.where(manager: true).order('last_name ASC')
    @employee = Employee.new
    @tbd_employees = Employee.joins(:position, :team).where("positions.name = 'TBD' OR teams.name = 'TBD'")
  end
end

app/helpers/allowances_helper.rb
module AllowancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/departements_helper.rb
module DepartementsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payslips_helper.rb
module PayslipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_navigation.html.erb
<button class="menu-icon fixed bg-gray-800 text-pink-200 rounded-full shadow-lg shadow-gray-800/50 text-4xl top-5 left-4 z-10 cursor-pointer">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 h-10 px-2 rounded-md">
      <path d="M18.75 12.75h1.5a.75.75 0 000-1.5h-1.5a.75.75 0 000 1.5zM12 6a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5A.75.75 0 0112 6zM12 18a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5A.75.75 0 0112 18zM3.75 6.75h1.5a.75.75 0 100-1.5h-1.5a.75.75 0 000 1.5zM5.25 18.75h-1.5a.75.75 0 010-1.5h1.5a.75.75 0 010 1.5zM3 12a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5A.75.75 0 013 12zM9 3.75a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5zM12.75 12a2.25 2.25 0 114.5 0 2.25 2.25 0 01-4.5 0zM9 15.75a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5z" />
  </svg>
</button>

<main class="sidebar fixed top-0 bottom-0 lg:left-0 w-[288px] overflow-x-auto overflow-y-auto text-center bg-gray-900 transform transition-transform duration-300 ease-in-out translate-x-[-100%] z-30">
  <div class="text-gray-100 text-xl">
    <div class="p-2.5 mt-1 flex items-center">
    <div class="flex flex-row">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 h-10 px-2 py-1 rounded-md bg-rose-600">
        <path fill-rule="evenodd" d="M4.5 2.25a.75.75 0 000 1.5v16.5h-.75a.75.75 0 000 1.5h16.5a.75.75 0 000-1.5h-.75V3.75a.75.75 0 000-1.5h-15zM9 6a.75.75 0 000 1.5h1.5a.75.75 0 000-1.5H9zm-.75 3.75A.75.75 0 019 9h1.5a.75.75 0 010 1.5H9a.75.75 0 01-.75-.75zM9 12a.75.75 0 000 1.5h1.5a.75.75 0 000-1.5H9zm3.75-5.25A.75.75 0 0113.5 6H15a.75.75 0 010 1.5h-1.5a.75.75 0 01-.75-.75zM13.5 9a.75.75 0 000 1.5H15A.75.75 0 0015 9h-1.5zm-.75 3.75a.75.75 0 01.75-.75H15a.75.75 0 010 1.5h-1.5a.75.75 0 01-.75-.75zM9 19.5v-2.25a.75.75 0 01.75-.75h4.5a.75.75 0 01.75.75v2.25a.75.75 0 01-.75.75h-4.5A.75.75 0 019 19.5z" clip-rule="evenodd" />
      </svg>
      <h1 class="font-bold text-gray-200 text-[15px] ml-3">Manage my payroll</h1>
    </div>
      <div class="flex flex-col">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 h-10 cursor-pointer ml-28" id="close-icon">
            <path fill-rule="evenodd" d="M5.47 5.47a.75.75 0 011.06 0L12 10.94l5.47-5.47a.75.75 0 111.06 1.06L13.06 12l5.47 5.47a.75.75 0 11-1.06 1.06L12 13.06l-5.47 5.47a.75.75 0 01-1.06-1.06L10.94 12 5.47 6.53a.75.75 0 010-1.06z" clip-rule="evenodd" />
        </svg>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10 cursor-pointer ml-28" id="bookmark-icon">
          <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" />
        </svg>
      </div>
    </div>
    <div class="mt-2 bg-gray-600 h-[1px]"></div>
  </div>
    <div class="p-2.5 flex items-center rounded-md px-4 duration-300 cursor-pointer bg-gray-700" >
      <%= render 'search/form' %>
    </div>
    <div class="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-rose-600 text-white">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
        <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
        <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
      </svg>
      <span class="text-[15px] ml-4 text-gray-200 font-bold"><%= link_to 'Dashboard', root_path %></span>
    </div>
    <div class="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-rose-600 text-white">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
        <path fill-rule="evenodd" d="M1.5 7.125c0-1.036.84-1.875 1.875-1.875h6c1.036 0 1.875.84 1.875 1.875v3.75c0 1.036-.84 1.875-1.875 1.875h-6A1.875 1.875 0 011.5 10.875v-3.75zm12 1.5c0-1.036.84-1.875 1.875-1.875h5.25c1.035 0 1.875.84 1.875 1.875v8.25c0 1.035-.84 1.875-1.875 1.875h-5.25a1.875 1.875 0 01-1.875-1.875v-8.25zM3 16.125c0-1.036.84-1.875 1.875-1.875h5.25c1.036 0 1.875.84 1.875 1.875v2.25c0 1.035-.84 1.875-1.875 1.875h-5.25A1.875 1.875 0 013 18.375v-2.25z" clip-rule="evenodd" />
      </svg>
      <span class="text-[15px] ml-4 text-gray-200 font-bold"><%= link_to 'Department', departements_path %> </span>
    </div>
    <div class="my-4 bg-gray-600 h-[1px]"></div>
    <div class="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-rose-600 text-white" >
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
        <path fill-rule="evenodd" d="M8.25 6.75a3.75 3.75 0 117.5 0 3.75 3.75 0 01-7.5 0zM15.75 9.75a3 3 0 116 0 3 3 0 01-6 0zM2.25 9.75a3 3 0 116 0 3 3 0 01-6 0zM6.31 15.117A6.745 6.745 0 0112 12a6.745 6.745 0 016.709 7.498.75.75 0 01-.372.568A12.696 12.696 0 0112 21.75c-2.305 0-4.47-.612-6.337-1.684a.75.75 0 01-.372-.568 6.787 6.787 0 011.019-4.38z" clip-rule="evenodd" />
        <path d="M5.082 14.254a8.287 8.287 0 00-1.308 5.135 9.687 9.687 0 01-1.764-.44l-.115-.04a.563.563 0 01-.373-.487l-.01-.121a3.75 3.75 0 013.57-4.047zM20.226 19.389a8.287 8.287 0 00-1.308-5.135 3.75 3.75 0 013.57 4.047l-.01.121a.563.563 0 01-.373.486l-.115.04c-.567.2-1.156.349-1.764.441z" />
      </svg>
      <div class="flex justify-between w-full items-center">
        <span class="text-[15px] ml-4 text-gray-200 font-bold">Teams</span>
        <span class="text-sm" id="arrow">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6" id="arrow">
            <path fill-rule="evenodd" d="M12.53 16.28a.75.75 0 01-1.06 0l-7.5-7.5a.75.75 0 011.06-1.06L12 14.69l6.97-6.97a.75.75 0 111.06 1.06l-7.5 7.5z" clip-rule="evenodd" />
          </svg>
        </span>
      </div>
    </div>
    <div class="text-left text-sm mt-2 w-4/5 mx-auto text-gray-200 font-bold" id="submenu" >
      <% @teams.each do |t| %>
        <h1 class="cursor-pointer p-2 hover:bg-rose-600 rounded-md mt-1">
          <%= link_to t.name, departement_team_path(t.departement, t) %>
        </h1>
      <% end %>
    </div>
    <div class="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-rose-600 text-white">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
        <path fill-rule="evenodd" d="M15.75 2.25H21a.75.75 0 01.75.75v5.25a.75.75 0 01-1.5 0V4.81L8.03 17.03a.75.75 0 01-1.06-1.06L19.19 3.75h-3.44a.75.75 0 010-1.5zm-10.5 4.5a1.5 1.5 0 00-1.5 1.5v10.5a1.5 1.5 0 001.5 1.5h10.5a1.5 1.5 0 001.5-1.5V10.5a.75.75 0 011.5 0v8.25a3 3 0 01-3 3H5.25a3 3 0 01-3-3V8.25a3 3 0 013-3h8.25a.75.75 0 010 1.5H5.25z" clip-rule="evenodd" />
      </svg>
      <span class="text-[15px] ml-4 text-gray-200 font-bold">Logout</span>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>ManageMyPayroll</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags 'application' %>
  </head>

  <body class="bg-rose-200 text-gray-900 relative">
      <%= render 'layouts/navigation' %>
      <main class="main-container mx-auto max-w-7xl pt-10 ml-0 min-h-screen h-full">
          <%= turbo_frame_tag "modal" %>
          <%= yield %>
      </main>

  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="p-6 sm:p-10 space-y-6 h-screen w-screen">
  <div class="flex flex-col space-y-6 md:space-y-0 md:flex-row justify-between">
      <h1 class="text-4xl font-semibold mb-2">Dashboard</h1>
      <%= link_to 'Create new employee', new_employee_path, data: { turbo_frame: "modal" }, class:'flex justify-center bg-red-500 hover:bg-red-700 font-bold py-2 px-4 rounded' %>
  </div>
  <section class="grid md:grid-cols-2 xl:grid-cols-4 gap-6">
    <div class="flex items-center p-8 bg-white shadow rounded-lg">
      <div class="inline-flex flex-shrink-0 items-center justify-center h-16 w-16 text-purple-600 bg-purple-100 rounded-full mr-6">
        <svg aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-6 w-6">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
        </svg>
      </div>
      <div>
        <span class="block text-2xl font-bold"><%= @employees_count %></span>
        <span class="block text-gray-500">Employees</span>
      </div>
    </div>
    <div class="flex items-center p-8 bg-white shadow rounded-lg">
      <div class="inline-flex flex-shrink-0 items-center justify-center h-16 w-16 text-purple-600 bg-purple-100 rounded-full mr-6">
        <svg aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-6 w-6">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
        </svg>
      </div>
      <div>
        <span class="block text-2xl font-bold"><%= @managers.count %></span>
        <span class="block text-gray-500">Managers</span>
      </div>
    </div>
  </section>
  <section class="grid md:grid-cols-2 xl:grid-cols-4 xl:grid-rows-3 xl:grid-flow-col gap-6">
    <div class="row-span-3 bg-white shadow rounded-lg">
      <div class="flex items-center justify-between px-6 py-5 font-semibold border-b border-gray-100">
        <span>All employees</span>
      </div>
      <div class="overflow-y-auto" style="max-height: 24rem;">
        <ul class="p-6 space-y-6">
          <% @employees.each do |employee| %>
            <li class="flex items-center">
              <div class="h-10 w-10 mr-3 bg-gray-100 rounded-full overflow-hidden">
                <%= image_tag(employee.avatar, class: "w-full h-full object-cover") %>
              </div>
              <span class="flex-1 w-1/2 break-words text-gray-600"><%= link_to employee.fullname, employee_path(employee) %></span>
              <span class="flex-1 w-1/2 break-words text-end  ml-auto font-semibold"><%= employee.departement.name %></span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="row-span-3 bg-white shadow rounded-lg">
      <div class="flex items-center justify-between px-6 py-5 font-semibold border-b border-gray-100">
        <span>Managers</span>
      </div>
      <div class="overflow-y-auto" style="max-height: 24rem;">
        <ul class="p-6 space-y-6">
          <% @managers.each do |manager| %>
            <li class="flex items-center">
              <div class="h-10 w-10 mr-3 bg-gray-100 rounded-full overflow-hidden">
                <%= image_tag(manager.avatar, class: "w-full h-full object-cover") %>
              </div>
              <span class="flex-1 w-1/2 break-words text-gray-600"><%= link_to manager.fullname, employee_path(manager) %></span>
              <span class="flex-1 w-1/2 break-words ml-auto font-semibold text-end"><%= manager.departement.name %></span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </section>
  <% if @tbd_employees.present? %>
    <section class="grid md:grid-cols-2 xl:grid-cols-4 xl:grid-rows-3 xl:grid-flow-col gap-6">
      <div class="row-span-3 bg-teal-500 shadow rounded-lg">
        <div class="flex items-center justify-between px-6 py-5 font-semibold border-b border-gray-100">
          <span class="font-semibold">FOR ACTION - Information to be defined</span>
        </div>
        <div class="overflow-y-auto" style="max-height: 24rem;">
          <ul class="p-6 space-y-6">
            <% @tbd_employees.each do |employee| %>
              <li class="flex items-center">
                <div class="h-10 w-10 mr-3 bg-gray-100 rounded-full overflow-hidden">
                  <%= image_tag(employee.avatar, class: "w-full h-full object-cover") %>
                </div>
                <span class="flex-1 w-1/2 break-words text-gray-600"><%= link_to employee.fullname, employee_path(employee) %></span>
                <span class="flex-1 w-1/2 break-words text-end  ml-auto font-semibold"><%= employee.departement.name %></span>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </section>
  <% end %>
</div>